ProjectRestro/ProjectRestro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('accounts.urls')),
    path('superuser/', include('superuser.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectRestro/home/urls.py
from django.urls import path

from home.views import (
    home,
    
    tagpage,
    
    adddish,

    menuPage,

    cart,

    crop_icon_image,
    add_dish_image_icon, 
    
    crop_major_image,
    add_dish_image_major,
    
    crop_secondary_image,
    add_dish_image_secondary,
    
    crop_tertiary_image,
    add_dish_image_tertiary,
    
    edit_dish,
    delete_dish,

    dish_page,
)

#Home Urls
urlpatterns = [
    path("", home, name='home'),

    path("add_tag/",tagpage, name="addtag"),

    path('add_dish/', adddish, name="addDish"),

    path("menu_page/", menuPage, name="menuPage"),

    path("cart/", cart, name="cart"),

    path('add_dish/addIconImage/<dish_id>',add_dish_image_icon , name="addIconImage"),

    path('dish/<dish_id>/', dish_page, name = 'dishPage'),
    
    path('add_dish/addIconImage/<dish_id>/cropIconImage/',crop_icon_image, name="crop_icon_image" ),

    path('add_dish/addMajorImage/<dish_id>',add_dish_image_major , name="addMajorImage"),
    path('add_dish/addMajorImage/<dish_id>/cropMajorImage/',crop_major_image, name="crop_major_image" ),

    path('add_dish/addSecondaryImage/<dish_id>',add_dish_image_secondary , name="addSecondaryImage"),
    path('add_dish/addSecondaryImage/<dish_id>/cropSecondaryImage/',crop_secondary_image, name="crop_secondary_image" ),

    path('add_dish/addTertiaryImage/<dish_id>',add_dish_image_tertiary , name="addTertiaryImage"),
    path('add_dish/addTertiaryImage/<dish_id>/cropTertiaryImage/',crop_tertiary_image, name="crop_tertiary_image" ),

    path('edit_dish/<dish_id>/', edit_dish, name="editDish"),

    path('edit_dish/<dish_id>/delete', delete_dish, name="deleteDish"),

    
]

ProjectRestro/home/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Models For Tags
class Tag(models.Model):
    COURSE_CATEGORY = (
        ('Beverage', 'Beverage'),
        ('Starter', 'Starter'),
        ('Main-Course', 'Main-Course'),
        ('Dessert', 'Dessert'),
    )
    name = models.CharField(max_length=255, null=True, unique=True)
    course = models.CharField(max_length=65, null=True, choices=COURSE_CATEGORY)
    def __str__(self):
        return self.name

# For Icon Image
def get_icon_image_file_path(self, filename):
    return f"DishImages/{str(self.pk)}/icon_image.png"

def get_default_icon_image():
    return 'Restro/default_icon_image.jpg'


# For Major Image
def get_major_image_file_path(self, filename):
    return f"DishImages/{str(self.pk)}/major_image.png"

def get_default_major_iamge():
    return 'Restro/default_major_image.jpg'

# For Secondary Image
def get_secondary_image_file_path(self, filename):
    return f"DishImages/{str(self.pk)}/secondary_image.png"

def get_default_secondary_iamge():
    return 'Restro/default_secondary_image.jpg'

# For Tertiary Image
def get_tertiary_image_file_path(self, filename):
    return f"DishImages/{str(self.pk)}/tertiary_image.png"

def get_default_tertiary_iamge():
    return 'Restro/default_tertiary_image.jpg'

# Model For Dishes (Need to add star rating and Image Description)
class Dishes(models.Model):
    CATEGORY_CHOICES = (
        ('Veg', "Veg")
        ,("Non-Veg", "Non-Veg")
    )
    ALCOHOL_CHOICES = (
        ('Yes', 'Yes'),
        ('No', 'No')
    )
    name = models.CharField(max_length=255, null=True, unique=True)
    date_created = models.DateTimeField(null=True, auto_now_add=True)
    description = models.TextField(blank=True) 
    price = models.FloatField(null=True)
    food_tag = models.ForeignKey(Tag, on_delete=models.DO_NOTHING, null=True)
    category = models.CharField(max_length=10, null=True, choices=CATEGORY_CHOICES)
    alcohol = models.CharField(max_length=10, null=True, choices=ALCOHOL_CHOICES)
    icon_image = models.ImageField(null=True,blank=True, upload_to=get_icon_image_file_path, default=get_default_icon_image)
    major_image = models.ImageField(null=True,blank=True, upload_to=get_major_image_file_path, default=get_default_major_iamge)
    major_description = models.CharField(max_length=40, blank=True)
    secondary_image = models.ImageField(null=True,blank=True, upload_to=get_secondary_image_file_path, default=get_default_secondary_iamge)
    secondary_description = models.CharField(max_length=40, blank=True)
    tertiary_image = models.ImageField(null=True,blank=True,  upload_to=get_tertiary_image_file_path, default=get_default_tertiary_iamge)
    tertiary_description = models.CharField(max_length=40, blank=True)
    dish_view = models.IntegerField(default=0, null=True,blank=True)
    
    def __str__(self):
        return self.name


#Model For Cart
class Cart(models.Model):
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Delivered', 'Delivered'),
        ('Canelled', 'Canelled'),
    )
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered_dish = models.ForeignKey(Dishes, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    quantity = models.IntegerField(null=True)
    total_amount = models.FloatField(null=True)
    table_number = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=100, null=True, choices=STATUS_CHOICES, default='Pending')

    def __str__(self):
        return f"{self.customer.username} Ordered {self.ordered_dish.name}"

ProjectRestro/home/views.py
import base64
import json
import os

import cv2
import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import files
from django.core.files.storage import FileSystemStorage, default_storage
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.db.models import Sum

from .decorators import allowed_users
from .forms import (
    TagForm,
    DishesForm, 
    DishesIconImageForm, 
    DishesMajorImageForm,
    DishesSecondaryImageForm,
    DishesTertiaryImageForm,
    EditDishForm,
    OrderForm,
)
from .models import (
    Tag, 
    Dishes,
    Cart
)
from requests.api import request

def home(request):
    return render(request, 'home/home.html')


# View For Tags
@login_required(login_url="login")
@allowed_users(allowed_roles=['admin'])
def tagpage(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            redirect ('addtag')
    else:
        form = TagForm()
    return render(request, 'home/tag.html', {'form':form})

# View For Add Dish
@login_required(login_url="login")
@allowed_users(allowed_roles=['admin'])
def adddish(request):
    tags = Tag.objects.all().order_by('name')
    if request.method == "POST":
        form = DishesForm(request.POST)
        if form.is_valid():
            dish = form.save()
            return redirect('addIconImage', dish.pk )
    else:
        form = DishesForm()
    return render(request, 'home/Add_New_Dish_Details.html', {'tags' : tags, "form" : form})

# View for showing the menu page
@login_required(login_url='login')
def menuPage(request):
    
    dishes = Dishes.objects.all()
    beverages = {}
    starters = {}
    main_course = {}
    desserts = {}
    tags = Tag.objects.all()

    for tag in tags:
        if tag.course == 'Beverage':
            beverages[tag.name] = tag.name
        elif tag.course == 'Starter':
            starters[tag.name] = tag.name
        elif tag.course == 'Main-Course':
            main_course[tag.name] = tag.name
        else:
            desserts[tag.name] = tag.name

    dishes = Dishes.objects.all()

    beverage_dishes = []
    starter_dishes = []
    main_course_dishes = []
    dessert_dishes = []

    for dish in dishes:
        if dish.food_tag.name in beverages:
            beverage_dishes.append(dish)
        elif dish.food_tag.name in starters:
            starter_dishes.append(dish)
        elif dish.food_tag.name in main_course:
            main_course_dishes.append(dish)
        else:
            dessert_dishes.append(dish)
    customer = request.user
    count_order = Cart.objects.filter(customer=customer).filter(status="Pending").count()

    context = {"beverages" : beverages, "starters" : starters, "main_course" : main_course, "desserts" : desserts, 'beverage_dishes' : beverage_dishes, 'starter_dishes' : starter_dishes, 'main_course_dishes' : main_course_dishes, 'dessert_dishes' : dessert_dishes, 'OrderCount' : count_order}
    return render(request, 'home/menu.html', context)



#Function To Get Table Number
def returnTableNumber(filepath):
    try:
        with open(filepath, 'r') as f:
            for line in f:
                words = ((line.strip()).split())
                if words:
                    first_word = words[0]
                    if first_word.isnumeric():
                        return first_word
    except Exception as e:
        return '0'
    else:
        return None


#Fucntion To Visit Menu Page.
@login_required(login_url='login')
def dish_page(request,*args, **kwargs):
    dish_id = kwargs.get('dish_id')
    dish = Dishes.objects.get(pk = dish_id)
    context = {}
    if request.POST:
        if not Cart.objects.filter(customer = request.user.id ,ordered_dish=dish_id, status="Pending"):
            form = OrderForm(request.POST, initial={
                'quantity' : 1
            })
            if form.is_valid():
                TABLE_PATH = request.POST.get('table_number')
                Cart.objects.create(
                    customer = form.cleaned_data['customer'],
                    ordered_dish = form.cleaned_data['ordered_dish'],
                    quantity = form.cleaned_data['quantity'],
                    total_amount = form.cleaned_data['total_amount'],
                    table_number = returnTableNumber(TABLE_PATH),
                )
                return redirect('menuPage')
        else:
            form = OrderForm(request.POST, initial={
                'quantity' : Cart.objects.filter(customer = request.user.id, ordered_dish=dish_id, status="Pending").first().quantity,
            })   
            if form.is_valid():
                TABLE_PATH = request.POST.get('table_number')
                Cart.objects.filter(customer = request.user.id, ordered_dish=dish_id, status="Pending").update(
                    quantity = form.cleaned_data['quantity'],
                    total_amount = form.cleaned_data['total_amount'],
                )
                return redirect('menuPage')
    else:
        if request.user.groups.all()[0].name != 'admin':
            dish.dish_view = dish.dish_view + 1
            dish.save()
        if not Cart.objects.filter(customer = request.user.id ,ordered_dish=dish_id, status="Pending"):
            form = OrderForm(initial={
                    'quantity' : 1,
            })
            context['InCart'] = 'false'
        else:
            form = OrderForm(initial={
                    'quantity' : Cart.objects.filter(customer = request.user.id ,ordered_dish=dish_id, status="Pending").first().quantity,
            })   
            context['InCart'] = 'true'
    customer = request.user
    count_order = Cart.objects.filter(customer=customer).filter(status="Pending").count()
    context['OrderCount'] = count_order
    context['dish'] = dish
    context['form'] = form
    return render(request , 'home/Dish_Page.html', context)


# Function To Edit Dish
@login_required(login_url="login")
@allowed_users(allowed_roles=['admin'])
def edit_dish(request, *args, **kwargs):
    tags = Tag.objects.all().order_by('name')
    dish_id = kwargs.get('dish_id')
    dish = Dishes.objects.get(pk=dish_id)
    context = {}
    context['tags'] = tags
    context['dish_name'] = dish.name
    if request.POST:
        form = EditDishForm(request.POST, instance=dish)
        if form.is_valid():
            form.save()
            return redirect('adminDishPage')
            
        else:
            form = EditDishForm(request.POST, instance=dish,
                initial={
                    'id': dish.id,
                    'name': dish.name,
                    'tag' : dish.food_tag,
                    'price': dish.price,
                    'category': dish.category,
                    'alcohol' : dish.alcohol,
                    'description': dish.description,
                    'icon_image' : dish.icon_image,
                    'major_image': dish.major_image,
                    'secondary_image': dish.secondary_image,
                    'tertiary_image': dish.tertiary_image,
                    'major_description': dish.major_description,
                    'secondary_description': dish.secondary_description,
                    'tertiary_description': dish.tertiary_description,                      
                }
            )
    else:
        form = EditDishForm(
                initial={
                    'id': dish.id,
                    'name': dish.name,
                    'tag' : dish.food_tag,
                    'price': dish.price,
                    'category': dish.category,
                    'alcohol' : dish.alcohol,
                    'description': dish.description,
                    'icon_image' : dish.icon_image,
                    'major_image': dish.major_image,
                    'secondary_image': dish.secondary_image,
                    'tertiary_image': dish.tertiary_image, 
                    'major_description': dish.major_description,
                    'secondary_description': dish.secondary_description,
                    'tertiary_description': dish.tertiary_description,                     
                }
            ) 

    context['form'] = form
    context['DATA_UPLOAD_MAX_MEMORY_SIZE'] = settings.DATA_UPLOAD_MAX_MEMORY_SIZE
    return render(request, 'home/Edit_Dish.html', context)


# Function To Delete A Dish
@login_required(login_url="login")
@allowed_users(allowed_roles=['admin'])
def delete_dish(request, *args, **kwargs):
    dish_id = kwargs.get('dish_id')
    dish = Dishes.objects.get(pk=dish_id)

    if(os.path.normpath(dish.icon_image.url) != "\media\Restro\default_icon_image.jpg"):
        dish.icon_image.delete()

    if(os.path.normpath(dish.major_image.url) != "\media\Restro\default_major_image.jpg"):
        dish.major_image.delete()

    if(os.path.normpath(dish.secondary_image.url) != "\media\Restro\default_secondary_image.jpg"):
        dish.secondary_image.delete()

    if(os.path.normpath(dish.tertiary_image.url) != "\media\Restro\default_tertiary_image.jpg"):
        dish.tertiary_image.delete()

    dish.delete()

    return redirect('adminDishPage')


# View For Cart
@login_required(login_url='login')
def cart(request, *args, **kwargs):
    context = {}
    order_in_cart = Cart.objects.filter(customer=request.user.id)
    total_order =  Cart.objects.filter(customer=request.user.id).aggregate(total = Sum('total_amount'))
    customer = request.user
    count_order = Cart.objects.filter(customer=customer).filter(status="Pending").count()
    context['OrderCount'] = count_order
    context['Total_Price'] = total_order['total']
    context['orders'] = order_in_cart
    return render(request, 'home/cart.html', context)

# View For Add Icon Image

# Address Where All The Temp Icon Image Are Stored 
TEMP_ICON_IMAGE_NAME = "temp_icon_image.png"

ProjectRestro/home/templates/home/Add_New_Dish_Details.html
{% extends 'base.html' %}

{% load static form_tags widget_tweaks %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/Add_New_Dish_Details.css' %}">
{% endblock %}

{% block body %}

    <div class = "Major-Container"></div>
    <div class = "Sub-Container">
        <p class="header">
            Creating Something New
        </p>
        <p class="sub-header">
            First Step Add Details
        </p>
        <form action="" method="POST" >
            {% csrf_token %}
            <div class="container">
                <div class = 'row' style="height: 100%">
                    <div class ='col row1toright' >
                        <div class = "form-group">
                            <label class = "label_" for="id_name">Dish's Name:</label>
                            <input class = "form-control" type="text" autocomplete='off' name="name" placeholder="Name Of The Dish" maxlength="255" required="" id="id_name">
                        </div>
                        <div class="form-group">
                            <label class="label_" for="id_tag">Tag:</label>
                            <select class="form-control"  name="food_tag" required="" id="id_food_tag">
                                <option value="" selected disabled hidden>Pick A Tag</option>
                                {% for tag in tags %}
                                    <option value="{{ tag.id }}"> {{ tag.name }} </option>
                                {% endfor %}
                            </select>
                            <a class="add-tags" href="{% url 'addtag' %}" onclick="window.open(this.href,'targetWindow',`toolbar=no, location=no, status=no, menubar=no,scrollbars=yes,resizable=yes,width=SomeSize,height=SomeSize`);return false;">
                                <i class="fa fa-plus" style="font-size: 30px; color: white;"></i>
                            </a>
                        </div>
                        <div class = "form-group">
                            <label class = "label_" for="id_price">Price:</label>
                            <input type="number" class = "form-control" min = '0' autocomplete="off" placeholder="Enter Amount in &#x20B9;" name="price" step="0.01" required="" id="id_price">
                        </div>
                        <div class="form-group">
                            <p class="categoryclass">Category:</p>
                            <label for="id_category_0">
                                <input type="radio" name="category" value="Veg" required="" id="id_category_0">
                                <svg style="width:42px;height:42px" viewBox="0 0 24 24">
                                    <path  d="M17,8C8,10 5.9,16.17 3.82,21.34L5.71,22L6.66,19.7C7.14,19.87 7.64,20 8,20C19,20 22,3 22,3C21,5 14,5.25 9,6.25C4,7.25 2,11.5 2,13.5C2,15.5 3.75,17.25 3.75,17.25C7,8 17,8 17,8Z" />
                                </svg>
                            </label>
                            <label for="id_category_1">
                                <input type="radio" name="category" value="Non-Veg" required="" id="id_category_1">
                                <svg style="width:42px;height:42px" viewBox="0 0 24 24">
                                    <path  d="M20.16 12.73C22.93 9.96 22.57 5.26 19.09 3C17.08 1.67 14.39 1.66 12.36 2.97C10.6 4.1 9.63 5.86 9.46 7.68C9.33 9 8.83 10.23 7.91 11.15L7.88 11.18C6.72 12.34 6.72 14.11 7.81 15.19L8.8 16.18C9.89 17.27 11.66 17.27 12.75 16.18C13.72 15.21 15 14.68 16.39 14.53C17.76 14.38 19.1 13.78 20.16 12.73M6.26 19.86C6.53 20.42 6.44 21.1 5.97 21.56C5.39 22.15 4.44 22.15 3.85 21.56C3.58 21.29 3.44 20.94 3.42 20.58C3.06 20.56 2.71 20.42 2.44 20.15C1.85 19.56 1.85 18.61 2.44 18.03C2.9 17.57 3.59 17.47 4.14 17.74L6.62 15.31C6.76 15.5 6.92 15.72 7.1 15.9L8.09 16.89C8.3 17.09 8.5 17.26 8.76 17.41L6.26 19.86Z" />
                                </svg>
                            </label>
                        </div>
                        <div class="form-group">
                            <p class="alcoholclass">Alcohol:</p>
                            <label for="id_alcohol_0">
                                <input type="radio" name="alcohol" value="Yes" required="" id="id_alcohol_0">
                                <svg style="width:42px;height:42px" viewBox="0 0 24 24">
                                    <path  d="M7.5,7L5.5,5H18.5L16.5,7M11,13V19H6V21H18V19H13V13L21,5V3H3V5L11,13Z" />
                                </svg>
                            </label>
                            <label for="id_alcohol_1">
                                <input type="radio" name="alcohol" value="No" required="" id="id_alcohol_1">
                                <svg style="width:42px;height:42px" viewBox="0 0 24 24">
                                    <path  d="M13.33 12.67L7.66 7L6.13 5.47L2.39 1.73L1.11 3L3 4.89V5L11 13V19H6V21H18V19.89L20.84 22.73L22.11 21.46L13.33 12.67M13 19V14.89L17.11 19H13M8.2 5L6.2 3H21V5L14.6 11.4L10.2 7H16.5L18.5 5H8.2Z" />
                                </svg>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row secondRow">
                    <p class="label_" id="id_description_tag">Description:</p>
                    
                    <div class="description-group">
                        <textarea placeholder="Add A Description About The Dish . . . . " name="description" id="id_description" ></textarea>   
                    </div>
                </div>
            </div>
            <div class="button-div">
                <input type="submit" class="animated" value="Submit"></input>
                <a class="cancel-link" href="#">Cancel</a>
            </div>
        </form> 
    </div>
{% endblock %}   

ProjectRestro/home/templates/home/MenuPage.html
{% extends "base.html" %}
{% load static widget_tweaks %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/MenuPage.css' %}">
{% endblock %}

{% block body %}
    {% include './navbar.html' %}
    <section class="Major-Container">
        <h1 class="ml15">
            <span class="word">Our</span>
            <span class="word">Menu</span>
        </h1>

        <div class="food-menu">
            {% for tag, dishes in EveryDish.Beverage.items %}
                <div class="container">
                     <h2 id="id_tag_name">{{ tag }}</h2>
                     <div class="wrapper">
                         {% for dish in dishes %}
                            <div class="card" onclick="DishPage({{ dish.id }})">
                                <img src="{{ dish.icon_image.url }}" alt="{{ dish.name }}">
                                <p id="id_dish_name">{{ dish.name }}</p>
                                <p id="id_dish_price">&#x20B9;{{ dish.price }}</p>
                            </div>
                         {% endfor %}
                     </div>
                </div>
            {% endfor %}

            {% for tag, dishes in EveryDish.Starter.items %}
                <div class="container">
                     <h2 id="id_tag_name">{{ tag }}</h2>
                     <div class="wrapper">
                         {% for dish in dishes %}
                            <div class="card" onclick="DishPage({{ dish.id }})">
                                <img src="{{ dish.icon_image.url }}" alt="{{ dish.name }}">
                                <p id="id_dish_name" >{{ dish.name }}</p>
                                <p id="id_dish_price">&#x20B9;{{ dish.price }}</p>
                            </div>
                         {% endfor %}
                     </div>
                </div>
            {% endfor %}
            {% for tag, dishes in EveryDish.MainCourse.items %}
                <div class="container">
                     <h2 id="id_tag_name">{{ tag }}</h2>
                     <div class="wrapper">
                         {% for dish in dishes %}
                            <div class="card" onclick="DishPage({{ dish.id }})">
                                <img src="{{ dish.icon_image.url }}" alt="{{ dish.name }}">    
                                <p id="id_dish_name" >{{ dish.name }}</p>
                                <p id="id_dish_price" >&#x20B9;{{ dish.price }}</p>
                            </div>
                         {% endfor %}
                     </div>
                </div>
            {% endfor %}
            {% for tag, dishes in EveryDish.Dessert.items %}
                <div class="container">
                     <h2 id="id_tag_name">{{ tag }}</h2>
                     <div class="wrapper">
                         {% for dish in dishes %}
                            <div class="card" onclick="DishPage({{ dish.id }})">
                                <img src="{{ dish.icon_image.url }}" alt="{{ dish.name }}">
                                <p id="id_dish_name" >{{ dish.name }}</p>
                                <p id="id_dish_price" >&#x20B9;{{ dish.price }}</p>
                            </div>
                         {% endfor %}
                     </div>
                </div>
            {% endfor %}
        </div>
    </section>  
{% endblock %}


{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script>
        anime.timeline({loop: 1})
            .add({
                    targets: '.ml15 .word',
                    scale: [14,1],
                    opacity: [0,1],
                    easing: "easeOutCirc",
                    duration: 800,
                    delay: (el, i) => 800 * i
            })
    </script>
    <script>
        function DishPage(DishId){
            console.log(DishId);
            var dish_url = "{% url 'home' %}" + 'dish/' + DishId
            console.log(dish_url);
            window.open(dish_url,"_self")
        }
    </script>
{% endblock %}

ProjectRestro/home/templates/home/cart.html
{% extends "base.html" %}

{% include static %}

{% block body %}
	{% include "./CSS/my_cart_css.html" %}
	
	{% include "./navbar.html" %}
	
<!-- INSIDE MASTER -->

	<div class="cartContainer ">
		<div class="heading ">My Cart ({{OrderCount}})</div>

		{% for order in orders %}
			<div class="item ">
				<div class="imageDetails ">
					<div class="imageContainer temp" style="background: url('{{ order.ordered_dish.icon_image.url }}'); background-size: cover; background-position: center;">
						<!-- image -->
					</div>
					<div class="countContainer ">
						<div class="removeItem "> - </div>
						<div class="itemCount ">
							{{ order.quantity }}
						</div>
						<div class="addItem "> + </div>
					</div>
				</div>


				<!-- ORDER DETAILS -->
				<div class="orderDetails  ">
					<div class="itemHeading ">
						{{ order.ordered_dish.name }}
					</div>
					<div class="dishInfo">
						<div class="itemTag ">{{ order.ordered_dish.food_tag.name }}</div>
						<div class="itemCategory ">category</div>
					</div>
					
					<div class="dishDetails ">
						{% if order.ordered_dish.description|length > 200 %}
							{{ order.ordered_dish.description|slice:200 }} . . .
						{% else %}
							{{ order.ordered_dish.description }}
						{% endif %}
					</div>

					<div class="priceInfo">
						<div class="itemPrice ">&#8377; {{ order.total_amount }}/-</div>
						<div class="removeFromCart "><div>Remove</div></div>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>

	<div class="priceContainer ">
		<div class="priceHeading ">PRICE DETAILS</div>
		<div class="pricingContainer">
			{% for order in orders %}
				<div class="pricing ">
					<div class="price ">{{ order.ordered_dish }}</div>
					<div class="value ">&#8377; {{ order.total_amount }}/-</div>
				</div>
			{% endfor %}
		</div>
		<div class="total">
			<div class="totalPrice ">Total Amount :</div>
			<div class="totalValue ">&#8377; {{Total_Price}}/-</div>
		</div>
	</div>
	


{% endblock %}

ProjectRestro/home/templates/home/menu_sidebar.html
{% block stylesheet %}

<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro&display=swap" rel="stylesheet">

{% endblock %}

<!-- its CSS is in Menu_card.css -->

<div class="sidebar">
	<div class="sidebar-content">
		<div class="sidebar-list">
			<ul class="sidebar-list-menu">
				<span class="sidebar-list-menu-active-bar"></span>
				<li><a href="#beverages" class="active" dd-active-tab="1">Beverages</a></li>
				<li><a href="#starters" dd-active-tab="2">Starters</a></li>
				<li><a href="#main-course" dd-active-tab="3">Main Course</a></li>
				<li><a href="#desserts" dd-active-tab="4">Desserts</a></li>
			</ul>
		</div>
	</div>
</div>